---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Box plot: Day of Week of Order by Department

```{r}
instacart %>%
  plot_ly(
    y = ~order_dow, color = ~department,
    type = "box") %>%
    layout(title = 'Day of Week of Order by Department', xaxis = list(title = 'Department'), 
           yaxis = list(title = 'Day of Week of Order', colors = "viridis"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Scatter plot: Number of Orders by Department

```{r}
instacart %>% 
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(
    x = ~department, y = ~n,
    type = "scatter", mode = "markers") %>%
  layout(title = 'Number of Orders by Department', xaxis = list(title = 'Department'), 
         yaxis = list(title = 'Number of Orders'), colors = "viridis")
```

### Bar plot: Number of Orders by Aisle

```{r}
instacart %>% 
  count(aisle) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n,
    type = "bar", mode = "markers") %>%
  layout(title = 'Number of Orders by Aisle', xaxis = list(title = 'Aisle'), 
         yaxis = list(title = 'Number of Orders'), colors = "viridis")
```

